set dotenv-load := true

deploy:
    @echo 'This is another recipe.'
    docker build --progress=plain -t retro-cube-lcd . && docker run --rm -v "$(pwd)/build:/output" retro-cube-lcd
    ssh "$PI_USER@$PI_IP" 'rm /home/pi/oled || true'
    scp build/oled "$PI_USER@$PI_IP:/home/pi/oled"

run-remote:
    @echo 'Deploy and run it on the Pi'
    just deploy
    ssh "ps aux | grep ./os | awk '{print $2}' | xargs kill -9"
    ssh "$PI_USER@$PI_IP" './oled'
