set dotenv-load := true

deploy:
    @echo 'This is another recipe.'
    docker build --progress=plain -t retro-cube-lcd . && docker run --rm -v "$(pwd)/build:/output" retro-cube-lcd
    ssh "$PI_USER@$PI_IP" 'rm /home/pi/lcd || true'
    scp build/lcd "$PI_USER@$PI_IP:/home/pi/lcd"
