FROM rust:latest

# Install cross-compilation tools
RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y gcc-arm-linux-gnueabihf pkg-config libsdl2-dev:armhf gcc-arm-linux-gnueabihf \
    && rm -rf /var/lib/apt/lists/*

# Add the ARM target for Rust
RUN rustup target add armv7-unknown-linux-gnueabihf

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
ENV PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig
ENV PKG_CONFIG_SYSROOT_DIR=/

# cache dependencies
COPY Cargo.toml Cargo.toml
COPY src ./src
COPY .cargo ./.cargo

# build for ARMv7
RUN cargo build --release --target=armv7-unknown-linux-gnueabihf

# prepare output
RUN mkdir -p /output
RUN cp target/armv7-unknown-linux-gnueabihf/release/os ./os

CMD ["cp", "os", "/output/os"]
